-- MySQL Script generated by MySQL Workbench
-- Tue Apr 19 12:30:04 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema carrera
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `carrera` ;

-- -----------------------------------------------------
-- Schema carrera
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `carrera` DEFAULT CHARACTER SET utf8 ;
USE `carrera` ;

-- -----------------------------------------------------
-- Table `carrera`.`coche`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `carrera`.`coche` ;

CREATE TABLE IF NOT EXISTS `carrera`.`coche` (
  `idcoche` VARCHAR(10) NOT NULL,
  `marca` VARCHAR(45) NULL,
  `modelo` VARCHAR(45) NULL,
  `peso` INT NULL,
  `potencia` INT NULL,
  PRIMARY KEY (`idcoche`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `carrera`.`piloto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `carrera`.`piloto` ;

CREATE TABLE IF NOT EXISTS `carrera`.`piloto` (
  `idpiloto` VARCHAR(10) NOT NULL,
  `dni` VARCHAR(45) NULL,
  `nombre` VARCHAR(45) NULL,
  `edad` INT NULL,
  `sexo` VARCHAR(45) NULL,
  `direccion` VARCHAR(45) NULL,
  `coche_idcoche` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`idpiloto`, `coche_idcoche`),
  CONSTRAINT `fk_piloto_coche1`
    FOREIGN KEY (`coche_idcoche`)
    REFERENCES `carrera`.`coche` (`idcoche`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `carrera`.`ruedas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `carrera`.`ruedas` ;

CREATE TABLE IF NOT EXISTS `carrera`.`ruedas` (
  `idruedas` VARCHAR(10) NOT NULL,
  `marca` VARCHAR(45) NULL,
  `modelo` VARCHAR(45) NULL,
  `dimensiones` INT NULL,
  `peso` INT NULL,
  `componente` VARCHAR(45) NULL,
  `estado` VARCHAR(45) NULL,
  `coche_idcoche` VARCHAR(10) NOT NULL,
  `fecha` DATE NULL,
  `sesion` INT NULL,
  PRIMARY KEY (`idruedas`, `coche_idcoche`),
  CONSTRAINT `fk_ruedas_coche1`
    FOREIGN KEY (`coche_idcoche`)
    REFERENCES `carrera`.`coche` (`idcoche`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `carrera`.`circuitos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `carrera`.`circuitos` ;

CREATE TABLE IF NOT EXISTS `carrera`.`circuitos` (
  `idcircuitos` VARCHAR(10) NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `ciudad` VARCHAR(45) NULL,
  `pais` VARCHAR(45) NULL,
  `longitud` INT NULL,
  `recordVuelta` INT NULL,
  `numCurvas` INT NULL,
  PRIMARY KEY (`idcircuitos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `carrera`.`campeonato`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `carrera`.`campeonato` ;

CREATE TABLE IF NOT EXISTS `carrera`.`campeonato` (
  `idcampeonato` VARCHAR(10) NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `anio` INT NULL,
  `numpilotos` INT NULL,
  `numcircuitos` INT NULL,
  `piloto_ganador` VARCHAR(45) NULL,
  PRIMARY KEY (`idcampeonato`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `carrera`.`carreras`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `carrera`.`carreras` ;

CREATE TABLE IF NOT EXISTS `carrera`.`carreras` (
  `idcarreras` VARCHAR(10) NOT NULL,
  `numvueltas` INT NULL,
  `vueltarapida` DOUBLE NULL,
  `numaccidentes` INT NULL,
  `fecha` DATE NULL,
  `circuitos_idcircuitos` VARCHAR(10) NOT NULL,
  `campeonato_idcampeonato` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`idcarreras`, `circuitos_idcircuitos`, `campeonato_idcampeonato`),
  CONSTRAINT `fk_carreras_circuitos1`
    FOREIGN KEY (`circuitos_idcircuitos`)
    REFERENCES `carrera`.`circuitos` (`idcircuitos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_carreras_campeonato1`
    FOREIGN KEY (`campeonato_idcampeonato`)
    REFERENCES `carrera`.`campeonato` (`idcampeonato`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `carrera`.`carreras_has_piloto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `carrera`.`carreras_has_piloto` ;

CREATE TABLE IF NOT EXISTS `carrera`.`carreras_has_piloto` (
  `carreras_idcarreras` VARCHAR(10) NOT NULL,
  `piloto_idpiloto` VARCHAR(10) NOT NULL,
  `vueltarapida` DOUBLE NULL,
  PRIMARY KEY (`carreras_idcarreras`, `piloto_idpiloto`),
  CONSTRAINT `fk_carreras_has_piloto_carreras1`
    FOREIGN KEY (`carreras_idcarreras`)
    REFERENCES `carrera`.`carreras` (`idcarreras`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_carreras_has_piloto_piloto1`
    FOREIGN KEY (`piloto_idpiloto`)
    REFERENCES `carrera`.`piloto` (`idpiloto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
